# Use the official Golang image as the base image
FROM golang:1.20-alpine

# Set the working directory
WORKDIR /app

# Copy the go.mod and go.sum files for managing dependencies
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Expose the service port
EXPOSE 8080

# Run the service
RUN go build -o ledger_service ./cmd/.

# run binary
ENTRYPOINT [ "./ledger_service" ]


