version: "3.9"

networks:
  default:
    name: ledger-network

services:
  ledgerservice: # ledger service
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DB: &PGDATABASE "ledger"
      POSTGRES_USER: &PGUSER "postgres"
      POSTGRES_PASSWORD: &PGPASSWORD "postgres"
      POSTGRES_HOST: &PGHOST "postgres"
      POSTGRES_PORT: &PGPORT "5432"
      PGSSLMODE: &PGSSLMODE "disable"
      PORT: &PORT "8080"
  postgres: # postgres service
    networks:
      - default
    image: postgres:14-alpine 
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_DB: *PGDATABASE
      POSTGRES_USER: *PGUSER
      POSTGRES_PASSWORD: *PGPASSWORD
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/

volumes:
  pgvolume: # declare a named volume to persist DB data